version: '3.8'

services:
  remedium-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - easypanel

  remedium-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file:
      - .env
    expose:
      - '${PORT}'
    depends_on:
      - remedium-db
    networks:
      - easypanel

volumes:
  db-data:

networks:
  easypanel:
    external: true
