version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: remedium-db
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # command: npx prisma db push
    container_name: remedium-api-prod
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - prisma
    volumes:
      - ./src:/app/src
  prisma:
    container_name: prisma-studio
    ports:
      - '5556:5556'
    depends_on:
      - db
    build:
      context: ./prisma
      dockerfile: Dockerfile
    command: npx prisma db push
