FROM node:18-alpine 

WORKDIR /app

COPY .env ./

COPY package*.json ./

RUN yarn install

COPY . .

RUN npx prisma generate

RUN yarn build

USER node

CMD ["sh", "-c", "npx prisma db push --skip-generate && yarn start:prod"]
