FROM node:18-alpine 

WORKDIR /app

COPY .env ./

COPY package*.json ./

RUN npm ci

COPY . .


RUN npx prisma generate
RUN npm run build

RUN npm install --global prisma

USER node

CMD ["sh", "-c", "npx prisma db push --skip-generate && npm run start:prod"]
