services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=remedium
    container_name: remedium-db
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - easypanel
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: remedium-api-prod
    restart: always
    env_file:
      - .env
    expose:
      - '${PORT}'
    depends_on:
      - db
    networks:
      - easypanel
volumes:
  db-data:
networks:
  easypanel:
    external: true
    name: easypanel
