FROM node:22-alpine AS development

# Working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN yarn install



# Copy the application code
COPY . .

# Start the application
CMD ["sh", "-c", "yarn db:deploy && yarn run start:dev"]