###################
# BUILD STAGE
###################

FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
RUN npx prisma generate

###################
# DEVELOPMENT STAGE
###################

FROM node:22-alpine AS development

WORKDIR /app


COPY --chown=node:node --from=builder /app/node_modules ./node_modules
COPY --chown=node:node --from=builder /app/. .

#USER node

CMD ["yarn", "start:dev"]
