version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: remedium-db
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # command: npx prisma db push
    container_name: remedium-api-prod
    restart: always
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
