###################
# BUILD STAGE
###################

FROM node:22-slim AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .


###################
# DEVELOPMENT STAGE
###################

FROM node:22-slim AS development

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN apt-get update && apt-get install -y procps openssl && rm -rf /var/lib/apt/lists/*

# NÃO gere o prisma aqui (evita gerar pro host)
CMD ["sh", "-c", "npx prisma generate && yarn start:dev"]
