version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: remedium-db
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: remedium-api-dev
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - prisma
    volumes:
      - ./src:/app/src

  prisma:
    container_name: prisma-studio
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '5556:5556'
    depends_on:
      - db
    build:
      context: ./prisma
      dockerfile: Dockerfile
      target: development
    command: bash -c "npx prisma studio --port 5556"
