services:
  db:
    image: postgres:latest
    container_name: remedium-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remedium
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: remedium-api-dev
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .git/
    depends_on:
      db:
        condition: service_healthy
    command: yarn start:dev

  prisma:
    container_name: prisma-studio
    build:
      context: ./prisma
      dockerfile: Dockerfile
      target: development
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '5556:5556'
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "npx prisma studio --port 5556"

volumes:
  db-data:
