FROM node:18-alpine 

WORKDIR /app

COPY .env ./

COPY package*.json ./

RUN npm install

COPY . .


RUN npx prisma generate

RUN npm run build

USER node

CMD ["sh", "-c", "npx prisma db push --skip-generate && npm run start:prod"]
